project:
  create: true
  name: gepaplexx

applications:

  ################## PATCH OPERATOR #############################
  patchOperator:
    name: patch-operator
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-patch-operator
      targetRevision: "0.1.*"
      helm:
        parameters:
          - name: "subscription.installPlanApproval"
            value: "manual"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ################## SEALED SECRETS OPERATOR ####################
  sealedSecretsOperator:
    name: sealed-secrets-operator
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gp-infrastructure
      create: false
    source:
      chart: sealed-secrets
      repoURL: https://bitnami-labs.github.io/sealed-secrets
      targetRevision: "2.7.*"
      helm:
        parameters:
          - name: containerSecurityContext.enabled
            value: 'false'
          - name: podSecurityContext.enabled
            value: 'false'
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ###################### IDENTITY PROVIDER ######################
  identityProvider:
    name: identity-provider
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-identity-provider
      targetRevision: "1.2.*"
      helm:
        parameters:
          - name: "google.clientSecret"
            value: "AgCJgFJp0xS6qm+UkBVnagUOorI7S7WcLtiOu2c6DzKUTTihA4zaohjER/ugHlCgN7HCW0gaTmhT8TLPsXyk4LVBUM+4ntASZGRcxWhF8MhHX97sdlNPvgDS7XRceLBeLVoxAfwkY/YsOcosb3O5v1t+gPr0BM2sZZ+mB03KpKmLmAStvlgbmZ0rtQa5RqUe8AaJ2JqfxiP9+6EHiFv2RLNoP0uUPDmd5npA7/lOJSyIE9Lu52dDzeW0uE9MrxhmtNJaFygZDeU86GjiMwkiWdFXTliZeEkMilO463hxz+7C8FY2hPCEig0zy7L6gTYUKdYqgYrEhbPZ2JyukEZd1PQXs89JPkQI4DODHKxZ0VJpPzmj6UMQK0oQn6Ez+V7h7dqUykPpkNEBxBfpZ+B77tUpLdnM22jzpxBEa2yy8abMVa+qhRNjLutDIlGxo7UaaEKZS9JBE9C2a+D4MnJWhTBcZB/N5UvObGn/aKewk1GCazm9ao1JEBmy3nGQcb3U473c5nNI93nrRl/MP/ugSuv65SF4Ck4aEdeadjU8kr/XG7uFjQoxvOKt9cs9XdklQFZmPsTcW0ne6RXpRAF8xSHCjGXHSgvVvE9atSVg7fFkacSMGVeRe8vwg8hSt40psMIstRZpgQpDyGISUsMhhOak9IJOTQXuY4XB9y2m/rpLoCt5dMfxHYTBERuLjnlqhCItC+cV2ee7CXnrocQ/eU0djzVaKfCYfudMAfFM5bngIbpv1A=="
          - name: "google.clientId"
            value: "AgAJ64sLUFF1PmdpKg/RlLjfiiWxXodCBipN9xTQLfpJUi0XQbZdEWl/Ncwm1x3wh8D8n1EIJhzq7Sm5eBtEC6jakPOHLy1eEN5kUd+N0BGH91YOw08HxPHwXocUeNCBd3oBg713h9nZPaOwf8xVXPKQ6BhqchY8X5BAMQIiOGZP9d8cnWh1aRKY7OTkXuRnQY7wpDSiDZ0iVHdVvjVyA8bzP5ASSEw4N6MdRwEAqzRmcMfS24gaxBd/u7Fd4WuyryNPxyFXY8evABiyEFhjCCgE8v71MUqEqWyFhmNmsrXMAh1+esoNPJ6TQUVHVtOtXDtCxdRqgyHIeEhb4/1Gh7o6XV440G6lLhZbQhkG1qGW2ljdriRVBkzUQLGB8EbTByCxx/NjkMYLEP8AnT5zTDVOJECaComc9KHDILMSS4ad/1DofEAbXIghDXdXFWIPnXH2JU+T8xyQP5xyFt0sNPPWqwoaWfeQA1bV9ItE2dMHpXjZaUuI7DXfFbifaSC1SpYIbggSIp0D+CRrARxJGZzgkN1uuLcQ9XkjihX3lGKXrbtGvdCZibj0xxVemWbQss4Le3sPp1anudab5wUc+3bfe15ekRte6UXHfL4Wy7to4SmkKJpxoAm6PFdCABtc4SLJ6gZuLeK4BVbskhPDH5K6gC6I91lGfLHlaVt3f3PK3753vavKewOIvIDRLvzdbN2pLIdeqpFaQr1C7mLJzYPdR9VavPdPJq6b02CpQKsQcbssteRhprlMmqDg7ME5x++xpduXPyZ/WULoqmT5/aYFJNPkRpzr6W8="
          - name: "google.restrDomain"
            value: "AgAmoSVl/ApqPIRvaiUD+U+sKrutv3/+c+aBWMP6akX+2XMnSk7hTTBX9Ljl3KSkWoDvs61CZWbyIdZPXl4Jkpf6DPlUuHPkXyxbwY16PfdxZYXG0oOLFQhXSakdH++jFGuK+y8myzL+913+JNqVjU20IYojPE827Y+H+7ngjUlyWceAM9wP0Asjw4nVgGrNOUTsN2kr92ZtpK/gc5RFRw2WyazXWjlSmsRruYFrOt+1d9Z/OQ2srec9atE0kb9M30b6uQtuNPv4WkEn6wkbE6ZeoASNxFpQbWVvsw7gavW55eY5RO9nzDx03IOcn/7bFCXToOFVK16P8kUC/4/klSn9KnzobEl0ADGO9PR2xLgsT2UpDepnSzhFFjJdCeSqEVO3nlXh1/JynZKORhhMy36WjjEI9y7KhFI0doxpXPK/tQfynqIbO7RjuTuwYDx5gDO02uDNgMPLa+1/xwnrnw9s5uOyZ2ZhmUEQuBjksij3lVPuiZypT7UU89KhCChoOdVGpPfKueChXHYAS92SmvGWHBHh4znCRTUM4npwXN1CXYTB+8c9QI4QpkYgXW0bZuu9Hxt1QLk6ltr8/m0P72B8/S8eKdlj/4EwnFhl0YOVHYGin+9LcJGhmQY+lkegRivKD7HTJXNQWuVXfGZcAc6YomAr40iRo5I2Uq3OitQQjSe3+/ByzTZFQtCnmUgabHgTN2jBUZDR4AzTYu8="
          - name: "google.enable"
            value: "true"
          - name: "git.clientSecret"
            value: "AgAWE6HCQQoW1LQEoYUMV+bYbZ6o2y6nBYQ4JbqW2S1XH0cr0rPzoIgzp6+zg457XSCeHB90B/bgdeiVlzZJBJuglcrHJLO07penFcatPfEMpCvLuqXL2aoO6CGx81u68/rt0rWIdsupppyh0UkndDI+pqQmUcvkguSuDvMeURJtHacenS4DYPvtLA5+wl7fjyUHPCHYt7UfuXlbTditrjkkjcy3zEtVkHT3VJrx74MpH96WEXKKJVXDMajYzxoxJ3ZhHoJraK+N4Zq6M5HaksnHgGp71LQibP/rmf4xH4UBuTqxfqDVhlO5rigpszJzAITOZ5S9aokNwKaZG9EPFAHjTJsMJQJlRXcCMBKEVus+cmis5upYUBA+Y/FUuQi7zVD8qItcPbfM+o5jyfxvAx5SHH65USFNOuLhk5CEBQ/yDID7lWBLZ6LFbOXra/3yaWJfV2rqxlaBe/VgFOEkYGayut80n6QKPs1r/nCCQ2+Lf6huWVwQTtkmJnqMM4Za0AVd/W6IRhWBn3Fp1PnhudBtN0xlVZPsFvIZnrqxIXgn6iynIm4DuSSe3gNft9TEC2GaKny6gWAWx7tFIuJ4yw73UARuNsFjSuhKkwCAYA+r7fjqvPdefsW3yHlv6zwWtXM3IKp4063j31SOSAajB/M0hzvyXa2vH92UIH0TiQ90OjOSXwHUq5iEM1jfOya80Mut6GBg/gYmtJ0qVzKZiWG53aYFHJ40jdyy9p47CY5xgxgD1/Bl4cuk"
          - name: "git.clientId"
            value: "AgBb7n8XX02FCaZQ4m/fXGt02hb8TvPCp9KKJbemBpS0nxBjIKY4PmA9/g7v8sdTRNDnECWFiM7PjV1KhovsTCi+6TgPsP6O5T9Wolihu0p0EjRTg65dyznuLqIjNioEtfz18ONOdRhHPZRS6Yc7k6vEJxoGCXy/SwztBI2+/lBGLBdY4W7L4/AbXhQbIukdOLYDW3n9OmueUuRmA55CO976lPeXON9r+WpV8RtXyQz9j+C+D+SquH3kKjZ3iW2d6jswWIr+u3edJL/DReHaxMxEjEf/SertfZ0EhP2N+E0OpflZUWyqYZqkGd+HkjXyIxcA+tKS8Wj/SYPdWKu4VzqZkHS/YBNKvDIubaP0R/nAzJ5CBgpD44WIeNNHjL+Fj+Nvbw5jsJ/MeOyuiEO9y1rwV7DH0DsJcjNBMmQp6A6XRMjX33AXxfP7YlKuR/vBReh/hYrhiEpKp89rZFpA5TypjueySW9ASlzzcymuEZM3PZPlR2Cn0SmNH9TmRtYiwiv/IBoQV8AV2tTLqObM0wqYym4ANDqbVdrmSE0bD/NjQh39DDGEGL3jjYwZM1TAJgA+cfKlNre3eoNaBwGz5Z4yHi7il+vrra7v8cjPT1Mt1hp5iKFbxMPUtBp8RA8wIi0l9kEFKHadNYO1nYwKJ8xrNapTh7/C8NHTaMKVMhe3khMxsXmj+KRMQ5B1aUFFm6AGVJvsWATUoMLe/MjPzwdppmyGcA=="
          - name: "git.restrOrgs"
            value: "AgB3tRM/CsAA2NM3o7f6oP8Ww8zU+cYw7I+sbZ0ranzBAB4b/ws+Ujtws6XSIoe3Jw+QbEIu4QEKEv7TU6WUTQ44qr67ZFcoqhWbz7gPZK97vl8NcJaVH6XEwZfu7oeJhYAyPnG/AqerIWokBIvrODnMk6L35lhmN8NoQL/I3HWcx+fObZ8UUU/blvSf2GA3AtZ6e5N+M64BaG5ZMnwFIKUzgywjyK8+mXlxin8TLZXUYmQtHETgNsnTZEeHRdCGT/UjiUJ57BC6eCd6OzfYFUuV3vEqrcwCTKl+cYJnkNKsRzLuQbMA7qpIW6468z2/86UIrVjxDEjuxybjHw5i6wCNLAYaDzcpvZeELcClq8wGbdz6eNpkHXiWoTLYWhApYKFCDMeN34VzUTagE9e034sHuKzT6KFsRk9w9e5HoMaX+pU16XmSdtR/A1dDMPjp7nCFCCUMkOpGr7DjWwM6A5K6dLjDyrJECmsPvxdIihfY8vkIL6zp+IUuIiT77Wz2aSL6tiMQTGJoS8AK37HfeKd8vmEUI3TmSDZDsLsC7Fz3LCo4U6kLHemeTj9zDNtwM9TyWtJQVCFuFYAItDW02NDDy2ZCLbr5QqfnYzTX0wYSWgkCddmDBbPuS9dKush02H0oGMrrVyqwzoUFIpuGqYYY4sQ4Zd7Zdb0fkQufwfAGvfrD3KDaVryTYDfEK5lvvgF8xPctsWc3Oi4Jh7ylBYSBkEG3mw=="
          - name: "git.enable"
            value: "true"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ###################### OAUTH GROUP SYNC  ######################
  oauthGroupSync:
    name: oauth-group-sync
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-oauth-group-sync
      targetRevision: "0.2.*"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true


  ####################### CLUSTER-CONFIG ########################
  clusterConfig:
    name: cluster-config
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-cluster-config
      targetRevision: "1.7.*"
      helm:
        parameters:
          - name: "argocd.workflowrepository.username"
            value: "AgB/rpE/pmxECYxI9xySBRehfpy7L22DcKOS+Vm5No11YBpTEhL77CyYJgW9Uh/3XP/wAeh9a625tLauoqcXK1Hj7ulInEus5IpyGK+N39lkRPMQ7WzV4mJKynL/iNx1qS/TM3lYLjl17hwFrTrKcSrQNoQvwCP06e6VYgqAH9EWH9+keq9lkVpwc9WjT3vn46QLzf0nh6hixLrcge5dy6caNpLQf3sMG2WFXNddxor1YwPf9VZn6m70fLXUPL7pZptthIKq4DbD+5Dl/wi1s+Ct6H3P4S76aCHB3wsyvOvPHnBFaDfpPY4nN4CC3IsDHXaSzvoXBJhCyGGQ4jGoA4C0hflYz3gua2fPWm+n2LgOAGwkYRw5LKSa94pGWC6lJXyFQmvvjcMzSmdEcBDbVLhOvJ/s5FH3W7ZOpxAy3u3zaI2jANQSxLgkdm7y/+NdQBhvU/ngu5/PMZtUyw88B6l1t/5NSClT5FQM8oIxrFtbJdElKeiAxCQx9QZd0QxyIrsLxd2mlsHxbBX7UJOCEm50A8WZztfHNaLL35xh7H4NpRjMNGR9Zlv+oNv9ldjugbEjdCcjF4rZTdaW7EdyHHSMfB9FbJ1neC4CJb7ET9yMzju7DNTTROm0Mz5kE1/5nOsZOvevHQqByyHz4gXA689tuon3SX6c80xp5oxZ3S8oNaEyhbG/cqKj59mbiTmjwMnSchWOCCv70I/cubGksjdfZw=="
          - name: "argocd.workflowrepository.sshPrivateKey"
            value: "AgBwcJjzKFTmrMHUIcZ0d7jkaH2wLaIixAMHIem/MH1hK+i0BUNx4/FFngJkjaDUqSnTClrJHqZryRppAFQdOlaicvdxlWJk9rnY4/6hXDHP8Z35o9Eqget7crmGEhg9/3lT6xJ+ye/5IBRATXXyumGjmjTzeA4swfEehJZGsDHkuvxKmf6+E92coBpLVq625Pi82BWemezrLQboL9Ytat2674YWZrkjhUg4zEWmudBva3aD7l6eMckj/GeyK69zXdN1g/RLz8m8zWfE6zj8jInc6mUIjwPZnzetwGc9Bh0BxnM/fjwv6RO916OMWLmFYkC1v3Hq6r39v8qX9fQYRdw5BP9gPYEi/drB8hawHic7XQO3R6Av7SrE2/cxn4HiVCSqZvnyYGqnwDQVW1z+addc+zsNczhAqFCA54ihm4g6IJFWx3pXGzPKElyJ6dkqL/xdlwwDw5tpKaoNVOra1kJEaw0xX/YK5cMw8BaGb3wnUWzOqGScvylrz915HFsOnOgt0cdG6/18XTWyjxOR/4VNRktG+6MLSqQBBJh6DhR1aBjFQpD0YoqyT6cPa2Z3DzBLGpg9zsMZkQe40AGQGx/LjvGpXWuiRrTnhVFWH/Cu6HCRcFb3By+G8fLttdnwtFH6gjqDzT2yQa3VDmh8ABAdxsFu+q9oW9iuxaUFQ8WehRzJJAxVBEaKD3HZZlhqBZbJxOcARLYvAb7GQsHQxKfa+qKNuKzio+H/3KTzBj5QLZkX00+s7u/R0i3ZN30jYwi8O3uTAQrTlpMhgp/Zsg7l+dhcfyPjfMXKPoqXn9ZvxjPoZMs7dKlH2ISmWwOX0iA/fte1ndcMfQolnqlow3Htf59JKxtoQ0oqTSHs5/uC9jzBSLKfAJkHhOsj9eoBvb+NwOGlkxCKJGnu2vN8nyBm6jCC8ZVx7L9/cdOvKFRHBcqN9NMkyppnUW9S+qe1hv57WiJlTUAbfavWQH7HCFaI7Vft3+Ksrw7RBPPA6KeoMPnP8S5lVbrsZGWQCDfMhcvKyyYPNXrdTzjtE1Oldki2AakqlKMRwnozoeB84uvyQghQLMPyB06WT7+iJ9KVVR14ixf17JRDEq4D9PZqC4AgFEmxyIpBmzvucECJhXOuHwGBHkQhfDDZr9qXvvIc9CEXNq2ESQIs5usk/z+LHNFpoGaAcdb8E4qA8Pxbcssgh8iX938HVPuTZIQHCJxG7s4/zAgNraIOP1vnUJYtpLRZq5fEz94/XtPgNGruMhiTFcL+Qq+LEnI+wJftQE+jWrzf1AuZ+bdG+FFam+2H73f3LWsDpAVYuraLnAt573yDPjq29BqZPEyj1xi4bCI4IlIsTO28kH6PY4ced1I3snJfsBQbZmEeMTN0TKpwHfoBJMUrJv4KmdGc0hxW6mFBQ5Ax6stYqgzRJb4Pp4Q3+1JZpYp7nPZf+LkMiVNOYDTUngpRoX3qGwS+dKnw2PT85kjMMcwU1A7XrA/tSOsSaEpdtKx8d3qUEtKRBZ5jgBla2eSOYh0ACSf4RWQ8Vlyss70cMfPWpxHaI4pfRtuHJrSZfH2eTCA8xdBOomTirZPsgvC2KyNkxBkpYLENt51A0+0PAID6R4LzBroahys+lGvnljqLOtlc5jCynTYJ5/jsQZ9xaJj57YnJe/vQzzUE6MqOh9Mrtzvmi83NUPFxAl5J898n7FfSIC6mjhHRIyNkiKStP+Q="
          - name: "argocd.notifications.argocdURL"
            value: "https://openshift-gitops-server-openshift-gitops.apps.steppe.gepaplexx.com"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ########################## ROOK/CEPH OPERATOR ##########################
  rookCephOperator:
    name: rook-ceph-operator
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: rook-ceph
      create: false
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-rook-ceph-operator
      targetRevision: "0.2.*"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ##################### IMAGE REGISTRY CACHE ######################
  internalRegistryMirror:
    name: openshift-registry-mirror
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-pull-through-cache
      targetRevision: "1.0.0"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ##################### CERT-MANAGER ######################
  certManager:
    name: cert-manager
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: cert-manager
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-cert-manager
      targetRevision: "1.7.*"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ##################### CERTIFICATES-PATCHES ######################
  certificatesPatches:
    name: certificate-patches
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-certificates-patches
      targetRevision: "2.0.*"
      helm:
        parameters:
          - name: "apiserver.customApiUrl"
            value: "api.steppe.gepaplexx.com"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ##################### CLUSTER-ISSUER ######################
  clusterIssuer:
    name: cluster-issuer
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: cert-manager
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-cluster-issuer
      targetRevision: "0.1.*"
      helm:
        parameters:
          - name: "solvers.dnsZones[0]"
            value: "steppe.gepaplexx.com"
          - name: "solvers.accessKeyId"
            value: "AKIATM2YI3GT5EKYOYDT"
          - name: "solvers.secretName"
            value: "steppe-route53-credentials-secret"
          - name: "solvers.secretAccessKey"
            value: "AgAea228aSorkEGT70irTNjE+KeQWt09SND3GAvRf2PihpsxJdS+H5BH+JLYUQwXjogaYcORF23rj41xK0zb+xFmKCdsOk0j5fLhPTFI/jf2WxiknWidvMfSXbgEpcq6NNE26oEk5ItefLL8IVWtJfohmLPhiYx904EyuilyLHpamDLBJsfemoKAOAfbfhtpYBBgSBff3hAEuRLSK4nv2bwLqm/LJK4aOTNwM2yL+bwK0xoF9e57GgwSzieI+aBygLX87zY1s5/yevPSQicf4kWjHIPzULUm4PGAvrvSo2LzrEKheLyUEdte0L3kCfKB7nSOFXIlmkJbkX8ob6zd6oDUvO7pszRGvlgzE2s6useGP9zKOlzfjgxMqfMjKiZcfT+ON6+pz3BdedUrxr6wIwd3TSWSm74WFu0fg8nOPfCY2mxnleisZhomwunopTz9K/eu6IbyZ1WNLTJPmtR/fCoHK9jowpzQEFgYQBN8a42VwXshwqUh8BfQcsSCSfHygINAj9n4W1XCvtTRYaFwvidhBFQD/4Td//5c1w1VmdLt3t7ryyZ2UQnp+WRwFBjqT3Z87tZEU97b4qMoiehtFOH/XUB4pyZAtr4haqZbNgSeCKJPkgbB3AiBu9V7+irWKp1w6vGWuH+eqg7uT7CW1teHOfPy8xkn7g4bevYxmTHeKAiP9zKmGenoY6z6M8Z0qW8AytvDk8i3XoH8TcsSb82KVtsJTVXBgZpxLC7pkCwyGu38pnGklNma"
          - name: "certificates.defaultIngress"
            value: "*.apps.steppe.gepaplexx.com"
          - name: "certificates.console"
            value: "console.apps.steppe.gepaplexx.com"
          - name: "certificates.api"
            value: "api.steppe.gepaplexx.com"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ##################### CONSOLE-PATCHES ######################
  consolePatches:
    name: console-patches
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-console-patches
      targetRevision: "0.3.*"
      helm:
        parameters:
          - name: "route.nameOverride"
            value: "true"
          - name: "route.hostname"
            value: "apps.steppe.gepaplexx.com"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
  ##################### KEYCLOAK-OPERATOR ######################
  keycloak-operator:
    name: keycloak-operator
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gp-sso
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-keycloak-operator
      targetRevision: "0.1.*"
      helm:
        parameters:
          - name: "subscription.installPlanApproval"
            value: "manual"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ##################### EXTERNAL SECRETS ######################
  external-secrets:
    name: external-secrets
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gp-external-secrets
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      targetRevision: "0.1.*"
      chart: gp-external-secrets-operator
      helm:
        parameters:
          - name: "subscription.installPlanApproval"
            value: "manual"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true