{
 "title": "ArgoCD - custom",
 "tags": [
  "Ansprechperson: Constantin Winkler",
  "Themengebiet: Betrieb"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(argocd_cluster_info, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "ArgoCD Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Reconcile Performance",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(argocd_app_reconcile_bucket{namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reconcilation Events Rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(argocd_app_reconcile_count{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Redis request duration / ms",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(namespace) (histogram_quantile(0.95, argocd_redis_request_duration_seconds_bucket{namespace=\"$namespace\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reconcile performance 95q for gitops argo",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum by(namespace) (histogram_quantile(0.95, argocd_app_reconcile_bucket{namespace=\"$namespace\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending Kubectl exec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by(pod) (argocd_kubectl_exec_pending{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ArgoCD Git Request Duration ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(argocd_git_request_duration_seconds_bucket{namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "K8s requests total / min",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum by(name) (rate(argocd_app_k8s_request_total{namespace=\"$namespace\"}[1m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Apps status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Sync events",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum by(name) (rate(argocd_app_sync_total{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Degraded | Missing Apps",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "sum by(name) (argocd_app_info{namespace=\"$namespace\", health_status!~\"Healthy|Progressing\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Loki be careful with time ranges",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 }
  },
  {
   "title": "Sync events",
   "type": "logs",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "{kubernetes_namespace_name=\"$namespace\"} |= `Initiated` != `dest-namespace` | json | line_format `{{.message}}` | pattern `<_> <_> <_> <_> <_> <_> '<version>'\" application=<application>` | line_format `{{.application}} synced to {{.version}}`"
    }
   ]
  },
  {
   "title": "Level / min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 56 },
   "targets": [
    {
     "expr": "sum by(level) (rate({kubernetes_namespace_name=\"$namespace\"} [1m]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Error log",
   "type": "logs",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "{kubernetes_namespace_name=\"$namespace\"} | level = `error` | json | line_format `{{.message}}`"
    }
   ]
  }
 ]
}