{
 "title": "ArgoCD - Custom",
 "tags": [
  "Ansprechperson: Constantin Winkler",
  "Themengebiet: Betrieb"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(argocd_cluster_info, namespace)"
    }
   },
   { "name": "Level", "label": "Level", "query": "info, warn, error, default" }
  ]
 },
 "panels": [
  { "title": "Apps status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sync events",
   "type": "timeseries",
   "description": "Zeigt die Syncevents an. Auch jene, die nicht von unserem Haupt ArgoCD verwaltet werden.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(name) (rate(argocd_app_sync_total{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Degraded | Missing Apps",
   "type": "state-timeline",
   "description": "Status timeline über degraded Applications",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(name) (argocd_app_info{namespace=\"$namespace\", health_status!~\"Healthy|Progressing\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "ArgoCD Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "K8s requests total / min",
   "type": "state-timeline",
   "description": "Änderungsrate(Farbe) von Objekten pro Applikation",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by(name) (rate(argocd_app_k8s_request_total{namespace=\"$namespace\"}[1m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis request duration / ms (Histogramm)",
   "type": "histogram",
   "description": "95 Quantill der Latenz zu Redis.\nAlles über 125ms ist sehr kritisch, im Regelfall sollten es so um die 20ms sein.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(namespace) (histogram_quantile(0.95, argocd_redis_request_duration_seconds_bucket{namespace=\"$namespace\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending Kubectl exec",
   "type": "timeseries",
   "description": "Requests an den KubeAPI Server, die noch nicht ausgeführt wurden. Im Regelfall 0",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum by(pod) (argocd_kubectl_exec_pending{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reconcile Performance",
   "type": "timeseries",
   "description": "\"Application reconciliation performance.\"\n\nVermutlich, wie schnell Änderungen an Ressourcen durchgeführt werden konnten.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(argocd_app_reconcile_bucket{namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ArgoCD Git Request Duration ",
   "type": "timeseries",
   "description": "Latenz zum git server. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(argocd_git_request_duration_seconds_bucket{namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reconcilation Events Rate",
   "type": "timeseries",
   "description": "Wie viele Änderungen pro Intervall durchgeführt wurden",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "sum(rate(argocd_app_reconcile_count{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Reconcile performance 95q for gitops argo",
   "type": "histogram",
   "description": "Konfidenzintervall in denen 95 % aller Werte liegen",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (argocd_app_reconcile_bucket{namespace=\"$namespace\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loki be careful with time ranges",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 }
  },
  {
   "title": "Level / min",
   "type": "timeseries",
   "description": "Wie viel Log Nachrichten mit dem jeweiligen Level pro Intervall geloggt wurden.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum by(level) (rate({kubernetes_namespace_name=\"$namespace\", level=~\"$Level\"} [1m]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Error log",
   "type": "logs",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "{kubernetes_namespace_name=\"$namespace\", level=~\"$Level\"} | json | line_format `{{.message}}`"
    }
   ]
  },
  {
   "title": "Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sync events",
     "type": "logs",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 42 },
     "targets": [
      {
       "expr": "{kubernetes_namespace_name=\"$namespace\"} |= `Initiated` != `dest-namespace` | json | line_format `{{.message}}` | pattern `<_> <_> <_> <_> <_> <_> '<version>'\" application=<application>` | line_format `{{.application}} synced to {{.version}}`"
      }
     ]
    }
   ]
  }
 ]
}