{
 "title": "Ceph OSDs",
 "tags": [
  "Themengebiet: Storage",
  "Ansprechperson: Simon Gartner"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "osd", "label": "OSD", "query": { "query": "label_values(ceph_daemon)" } },
   {
    "name": "rate_interval",
    "label": "Rate Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Ceph OSD Operation Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(ceph_osd_op{ceph_daemon=~\"osd.${osd}\"}[$rate_interval])",
     "legendFormat": "{{ceph_daemon}}"
    }
   ]
  },
  {
   "title": "Ceph OSD latency rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(ceph_osd_op_latency_sum{ceph_daemon=~\"osd.$osd\"}[$rate_interval])",
     "legendFormat": "{{ceph_daemon}}"
    }
   ]
  },
  {
   "title": "Ceph OSD Bytes Used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(ceph_osd_stat_bytes_used{ceph_daemon=~\"osd.$osd\"}[$rate_interval])",
     "legendFormat": "{{ceph_daemon}}"
    }
   ]
  }
 ]
}