{
 "title": "Demo Microservice Dashboard",
 "description": "Dashboard für demo-microservice. Verwendet micrometer metrics. Der metrics endpoint ist abrufbar unter <demo-mircoservice-route>/metrics",
 "tags": [
  "Applikation: demo-microservice",
  "Ansprechperson: Tobias Meindl",
  "Themengebiet: App"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": "label_values(jvm_memory_used_bytes{namespace=\"$namespace\", area=\"heap\"},id)"
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": "label_values(jvm_memory_used_bytes{namespace=\"$namespace\", area=\"nonheap\"},id)"
   },
   {
    "name": "jvm_buffer_pool",
    "label": "JVM Buffer Pools",
    "query": "label_values(jvm_buffer_memory_used_bytes{namespace=\"$namespace\"},id)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(demo_microservice_test_alert_active,namespace)"
    }
   },
   { "name": "log_level", "label": "log_level", "query": ".+" },
   { "name": "search" }
  ]
 },
 "panels": [
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{kubernetes_namespace_name=\"$namespace\"} |~ `$log_level` | json | line_format `{{.message}}` |~\"$search\""
    }
   ]
  },
  {
   "title": "Quick Facts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Test Alert",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "demo_microservice_test_alert_active{namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{namespace=\"$namespace\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{namespace=\"$namespace\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap used",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{namespace=\"$namespace\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{namespace=\"$namespace\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "I/O Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{namespace=\"$namespace\"}[1m]))",
     "legendFormat": "HTTP"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{namespace=\"$namespace\", status=~\"5..\"}[1m]))",
     "legendFormat": "HTTP - 5xx"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{namespace=\"$namespace\", status!~\"5..\"}[1m]))/sum(rate(http_server_requests_seconds_count{namespace=\"$namespace\", status!~\"5..\"}[1m]))",
     "legendFormat": "HTTP - AVG"
    },
    {
     "expr": "max(http_server_requests_seconds_max{namespace=\"$namespace\", status!~\"5..\"})",
     "legendFormat": "HTTP - MAX"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {}
   ]
  },
  {
   "title": "JVM Heap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{namespace=\"$namespace\", area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{namespace=\"$namespace\", area=\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{namespace=\"$namespace\", area=\"heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{namespace=\"$namespace\", area=\"nonheap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{namespace=\"$namespace\", area=\"nonheap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{namespace=\"$namespace\", area=\"nonheap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{namespace=\"$namespace\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{namespace=\"$namespace\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{namespace=\"$namespace\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "system_cpu_usage{namespace=\"$namespace\"}",
       "legendFormat": "system"
      },
      {
       "expr": "process_cpu_usage{namespace=\"$namespace\"}",
       "legendFormat": "process"
      },
      {
       "expr": "avg_over_time(process_cpu_usage{namespace=\"$namespace\"}[15m])",
       "legendFormat": "process-15m"
      }
     ]
    },
    {
     "title": "Load",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "system_load_average_1m{namespace=\"$namespace\"}",
       "legendFormat": "system-1m"
      },
      {
       "expr": "system_cpu_count{namespace=\"$namespace\"}",
       "legendFormat": "cpus"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_threads_live_threads{namespace=\"$namespace\"}",
       "legendFormat": "live"
      },
      {
       "expr": "jvm_threads_daemon_threads{namespace=\"$namespace\"}",
       "legendFormat": "daemon"
      },
      {
       "expr": "jvm_threads_peak_threads{namespace=\"$namespace\"}",
       "legendFormat": "peak"
      },
      {
       "expr": "process_threads{namespace=\"$namespace\"}",
       "legendFormat": "process"
      }
     ]
    },
    {
     "title": "Thread States",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_threads_states_threads{namespace=\"$namespace\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "GC Pressure",
     "type": "timeseries",
     "description": "The percent of time spent on Garbage Collection over all CPUs assigned to the JVM process.",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(jvm_gc_pause_seconds_sum{namespace=\"$namespace\"}[1m])) by (application, instance) / on(application, instance) system_cpu_count",
       "legendFormat": "CPU time spent on GC"
      }
     ]
    },
    {
     "title": "File Descriptors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "process_files_open_files{namespace=\"$namespace\"}",
       "legendFormat": "open"
      },
      {
       "expr": "process_files_max_files{namespace=\"$namespace\"}",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "repeat": "persistence_counts",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$jvm_memory_pool_heap",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 60 },
     "repeat": "jvm_memory_pool_heap",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"$namespace\", id=~\"$jvm_memory_pool_heap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{namespace=\"$namespace\", id=~\"$jvm_memory_pool_heap\"}",
       "legendFormat": "commited"
      },
      {
       "expr": "jvm_memory_max_bytes{namespace=\"$namespace\", id=~\"$jvm_memory_pool_heap\"}",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Non-Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$jvm_memory_pool_nonheap",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 68 },
     "repeat": "jvm_memory_pool_nonheap",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"$namespace\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{namespace=\"$namespace\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "commited"
      },
      {
       "expr": "jvm_memory_max_bytes{namespace=\"$namespace\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Collections",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_count{namespace=\"$namespace\"}[1m])",
       "legendFormat": "{{action}} ({{cause}})"
      }
     ]
    },
    {
     "title": "Pause Durations",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_sum{namespace=\"$namespace\"}[1m])/rate(jvm_gc_pause_seconds_count{namespace=\"$namespace\"}[1m])",
       "legendFormat": "avg {{action}} ({{cause}})"
      },
      {
       "expr": "jvm_gc_pause_seconds_max{namespace=\"$namespace\"}",
       "legendFormat": "max {{action}} ({{cause}})"
      }
     ]
    },
    {
     "title": "Allocated/Promoted",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(jvm_gc_memory_allocated_bytes_total{namespace=\"$namespace\"}[1m])",
       "legendFormat": "allocated"
      },
      {
       "expr": "rate(jvm_gc_memory_promoted_bytes_total{namespace=\"$namespace\"}[1m])",
       "legendFormat": "promoted"
      }
     ]
    }
   ]
  },
  {
   "title": "Classloading",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Classes loaded",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_classes_loaded_classes{namespace=\"$namespace\"}",
       "legendFormat": "loaded"
      }
     ]
    }
   ]
  }
 ]
}