{
 "title": "ExternalSecretOperator",
 "tags": [
  "Themengebiet: Security & Berechtigungen",
  "Ansprechperson: Simon Gartner",
  "Ansprechperson: Shahin Mahmody"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "namespace", "query": "gp-external-secrets" }
  ]
 },
 "panels": [
  {
   "title": "Status per secret",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(name) (externalsecret_status_condition{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sync calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by(name) (rate(externalsecret_sync_calls_total{namespace=\"$namespace\"}[$__rate_interval]) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sync Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum by(name) (rate(externalsecret_sync_calls_error{namespace=\"$namespace\"}[$__rate_interval]) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum by(container) (container_memory_usage_bytes{namespace=\"$namespace\"}) / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum by(container) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Namespace Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "{kubernetes_namespace_name=\"$namespace\"} | json | line_format `{{.message}}` |= `level` | json | line_format `{{.logger}} {{.msg}}`"
    },
    {
     "expr": "{kubernetes_namespace_name=\"$namespace\"} | json | line_format `{{.message}}` != `level`"
    }
   ]
  }
 ]
}