{
 "title": "Grafana",
 "description": "Grafana Metics Dashboards",
 "tags": [
  "Ansprechperson: Herbert Wirnsberger",
  "Themengebiet: Monitoring"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": "gp-grafana" },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(grafana_build_info,pod)"
    }
   },
   {
    "name": "version",
    "label": "Version",
    "query": {
     "query": "label_values(grafana_build_info,version)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "General Counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "description": "start time of the process",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{pod=\"$pod\"} * 1000"
    }
   ]
  },
  {
   "title": "Organisation Count",
   "type": "stat",
   "description": "total amount of orgs",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "grafana_stat_total_orgs{pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "User Count",
   "type": "stat",
   "description": "total amount of users",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "grafana_stat_total_users{pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Dashboard Count",
   "type": "stat",
   "description": "total amount of dashboards",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "grafana_stat_totals_dashboard{pod=\"$pod\"}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Logs for namespace $namespace",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{kubernetes_namespace_name=\"$namespace\"} | json | line_format \"Level: {{.level}}\\t\\tPod: {{.kubernetes_pod_name}}\\t\\tContainer: {{.kubernetes_container_name}}\\t\\tHost: {{.kubernetes_host}}\\t\\tPodIP: {{.kubernetes_pod_ip}}\\nMessage: {{.message}}\""
    }
   ]
  },
  {
   "title": "Grafana Plugin Request Total Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }
  },
  {
   "title": "Grafana Plugin Request Total Status",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "targets": [
    { "expr": "grafana_plugin_request_total", "legendFormat": "{{plugin_id}}-{{status}}" }
   ]
  },
  {
   "title": "CPU, Memory and File Descriptor Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "graph",
   "description": "Average user and system CPU time spent in seconds.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{pod=\"$pod\"}[5m]))",
     "legendFormat": "CPU Time"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "graph",
   "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_resident_memory_bytes{pod=\"$pod\"}[5m]))",
     "legendFormat": "Resident Mem"
    },
    {
     "expr": "avg(rate(process_virtual_memory_bytes{pod=\"$pod\"}[5m]))",
     "legendFormat": "Virtual Mem"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{pod=\"$pod\"}",
     "legendFormat": "Open FD"
    }
   ]
  },
  {
   "title": "Response Codes and Logins",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Response Statuses",
   "type": "graph",
   "description": "http response status",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grafana_api_response_status_total{pod=\"$pod\"}",
     "legendFormat": "API {{ code }}"
    },
    {
     "expr": "grafana_page_response_status_total{pod=\"$pod\"}",
     "legendFormat": "Page {{ code }}"
    },
    {
     "expr": "grafana_proxy_response_status_total{pod=\"$pod\"}",
     "legendFormat": "Proxy {{ code }}"
    }
   ]
  },
  {
   "title": "Login Counts",
   "type": "graph",
   "description": "api login counters",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grafana_api_login_post_total{pod=\"$pod\"}",
     "legendFormat": "POST"
    },
    {
     "expr": "grafana_api_login_oauth_total{pod=\"$pod\"}",
     "legendFormat": "OAuth"
    }
   ]
  },
  {
   "title": "Dataproxy Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Dashboard Get Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Dashboard Get Duration Quantiles",
   "type": "graph",
   "description": "summary for dashboard get duration",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "grafana_api_dashboard_get_milliseconds{pod=\"$pod\", quantile=\"0.5\"}",
     "legendFormat": "0.5"
    },
    {
     "expr": "grafana_api_dashboard_get_milliseconds{pod=\"$pod\", quantile=\"0.9\"}",
     "legendFormat": "0.9"
    },
    {
     "expr": "grafana_api_dashboard_get_milliseconds{pod=\"$pod\", quantile=\"0.99\"}",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "Dashboard Get Duration Avg [5 min]",
   "type": "graph",
   "description": "average dashboard get duration over 5 minutes",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(grafana_api_dashboard_get_milliseconds_sum{pod=\"$pod\"}[5m]) / rate(grafana_api_dashboard_get_milliseconds_count{pod=\"$pod\"}[5m])",
     "legendFormat": "0.5"
    }
   ]
  },
  {
   "title": "Dashboard Save Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Dashboard Save Duration Quantiles",
   "type": "graph",
   "description": "summary for dashboard save duration",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "grafana_api_dashboard_save_milliseconds{pod=\"$pod\", quantile=\"0.5\"}",
     "legendFormat": "0.5"
    },
    {
     "expr": "grafana_api_dashboard_save_milliseconds{pod=\"$pod\", quantile=\"0.9\"}",
     "legendFormat": "0.9"
    },
    {
     "expr": "grafana_api_dashboard_save_milliseconds{pod=\"$pod\", quantile=\"0.99\"}",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "Dashboard Save Duration Avg [5 min]",
   "type": "graph",
   "description": "average dashboard save duration over 5 minutes",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(grafana_api_dashboard_save_milliseconds_sum{pod=\"$pod\"}[5m]) / rate(grafana_api_dashboard_save_milliseconds_count{pod=\"$pod\"}[5m])",
     "legendFormat": "0.5"
    }
   ]
  },
  {
   "title": "Dashboard Search Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Dashboard Search Duration Quantiles",
   "type": "graph",
   "description": "summary for dashboard search duration",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "grafana_api_dashboard_search_milliseconds{pod=\"$pod\", quantile=\"0.5\"}",
     "legendFormat": "0.5"
    },
    {
     "expr": "grafana_api_dashboard_search_milliseconds{pod=\"$pod\", quantile=\"0.9\"}",
     "legendFormat": "0.9"
    },
    {
     "expr": "grafana_api_dashboard_search_milliseconds{pod=\"$pod\", quantile=\"0.99\"}",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "Dashboard Search Duration Avg [5 min]",
   "type": "graph",
   "description": "average dashboard search duration over 5 minutes",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(grafana_api_dashboard_search_milliseconds_sum{pod=\"$pod\"}[5m]) / rate(grafana_api_dashboard_search_milliseconds_count{pod=\"$pod\"}[5m])",
     "legendFormat": "0.5"
    }
   ]
  }
 ]
}