{
 "title": "Kyverno",
 "tags": [
  "Ansprechperson: Tobias Meindl",
  "Applikation: Kyverno",
  "Themengebiet: Security & Berechtigungen"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "search" },
   { "name": "log_level", "query": "error" }
  ]
 },
 "panels": [
  { "title": "ResourceUsage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "pod:container_cpu_usage:sum{namespace=\"gp-kyverno\"}\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"\", namespace=\"gp-kyverno\", container!=\"\", image!=\"\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rule Execution Success Rate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kyverno_policy_results_total{rule_result=\"pass\"})*100/sum(kyverno_policy_results_total{})"
    }
   ]
  },
  {
   "title": "Cluster Policies",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(kyverno_policy_rule_info_total{policy_type=\"cluster\"}==1) by (policy_name))"
    }
   ]
  },
  {
   "title": "Policies",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(kyverno_policy_rule_info_total{policy_type=\"namespaced\"}==1) by (policy_name))"
    }
   ]
  },
  {
   "title": "Background Scans Success Rate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kyverno_policy_results_total{rule_result=\"pass\", policy_background_mode=\"true\"})*100/sum(kyverno_policy_results_total{policy_background_mode=\"true\"})"
    }
   ]
  },
  {
   "title": "Validate Rules",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kyverno_policy_rule_info_total{rule_type=\"validate\"}==1)"
    }
   ]
  },
  {
   "title": "Mutate Rules",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kyverno_policy_rule_info_total{rule_type=\"mutate\"}==1)"
    }
   ]
  },
  {
   "title": "Generate Rules",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kyverno_policy_rule_info_total{rule_type=\"generate\"}==1)"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "{kubernetes_namespace_name=\"gp-kyverno\"} |~ `$log_level` | json | line_format `{{.message}}` |~\"$search\""
    }
   ]
  },
  {
   "title": "Policy-Rule Results",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Admission Review Results (per-rule)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kyverno_policy_results_total{rule_execution_cause=\"admission_request\"}) by (rule_result)",
       "legendFormat": "{{rule_result}}"
      }
     ]
    },
    {
     "title": "Admission Review Results (per-policy)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(sum(kyverno_policy_results_total{rule_execution_cause=\"admission_request\"}) by (policy_name, rule_result)) by (rule_result)",
       "legendFormat": "{{rule_result}}"
      }
     ]
    },
    {
     "title": "Policy Failures",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(sum(kyverno_policy_results_total{rule_result=\"fail\"}) by (policy_name, policy_type)) by (policy_type)",
       "legendFormat": "{{policy_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Policy-Rule Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Active Policies (by policy type)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count(count(kyverno_policy_rule_info_total{}==1) by (policy_name, policy_type)) by (policy_type)",
       "legendFormat": "{{policy_type}}"
      }
     ]
    },
    {
     "title": "Active Policies (by policy validation action)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count(count(kyverno_policy_rule_info_total{}==1) by (policy_name, policy_validation_mode)) by (policy_validation_mode)",
       "legendFormat": "audit"
      }
     ]
    },
    {
     "title": "Active Policies running in background mode",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count(count(kyverno_policy_rule_info_total{policy_background_mode=\"true\"}==1) by (policy_name, policy_type)) by (policy_type)",
       "legendFormat": "{{policy_type}}"
      }
     ]
    },
    {
     "title": "Active Namespaced Policies (by namespaces)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count(count(kyverno_policy_rule_info_total{policy_namespace!=\"-\"}==1) by (policy_name, policy_namespace)) by (policy_namespace)",
       "legendFormat": "{{policy_namespace}}"
      }
     ]
    },
    {
     "title": "Active Rules (by rule type)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count(kyverno_policy_rule_info_total{}==1) by (rule_type)",
       "legendFormat": "{{rule_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Policy-Rule Execution Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Average Rule Execution Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(kyverno_policy_execution_duration_seconds_sum{}) by (rule_type)",
       "legendFormat": "{{rule_type}}"
      }
     ]
    },
    {
     "title": "Average Policy Execution Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 9, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "clocks" } },
     "targets": [
      {
       "expr": "avg(sum(kyverno_policy_execution_duration_seconds_sum{}) by (policy_name, policy_type)) by (policy_type)",
       "legendFormat": "{{policy_type}}"
      }
     ]
    },
    {
     "title": "Overall Average Rule Execution Latency",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(kyverno_policy_execution_duration_seconds_sum{})"
      }
     ]
    },
    {
     "title": "Overall Average Policy Execution Latency",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(sum(kyverno_policy_execution_duration_seconds_sum{}) by (policy_name, policy_type))"
      }
     ]
    }
   ]
  },
  {
   "title": "Admission Review Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Avg - Admission Review Duration (by operation)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(kyverno_admission_requests_total{}) by (resource_request_operation)",
       "legendFormat": "Resource Operation: {{resource_request_operation}}"
      }
     ]
    },
    {
     "title": "Avg - Admission Review Duration (by resource kind)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 9, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(kyverno_admission_requests_total{}) by (resource_kind)",
       "legendFormat": "Resource Kind: {{resource_kind}}"
      }
     ]
    },
    {
     "title": "Rate - Incoming Admission Requests (last 5m)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(kyverno_admission_requests_total{}[5m]))"
      }
     ]
    },
    {
     "title": "Avg - Overall Admission Review Duration",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(kyverno_admission_review_duration_seconds_sum{})"
      }
     ]
    }
   ]
  },
  {
   "title": "Policy Changes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Policy Changes (by change type)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kyverno_policy_changes_total{}) by (policy_change_type)",
       "legendFormat": "Change type: {{policy_change_type}}"
      }
     ]
    },
    {
     "title": "Policy Changes (by policy type)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 9, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kyverno_policy_changes_total{}) by (policy_type)",
       "legendFormat": "{{policy_type}}"
      }
     ]
    },
    {
     "title": "Total Policy Changes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kyverno_policy_changes_total{})"
      }
     ]
    },
    {
     "title": "Rate - Policy Changes Happening (last 5m)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(kyverno_admission_requests_total{}[5m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Admission Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Admission Requests (by operation)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kyverno_admission_requests_total{}) by (resource_request_operation)",
       "legendFormat": "Resource Operation: {{resource_request_operation}}"
      }
     ]
    },
    {
     "title": "Admission Requests (by resource kind)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 9, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kyverno_admission_requests_total{}) by (resource_kind)",
       "legendFormat": "Resource Kind: {{resource_kind}}"
      }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 46 },
   "options": {
    "content": "# Kyverno\nA Kubernetes-native policy management engine\n\n#### About this dashboard\n\nThis dashboard represents generic insights which can be extracted and made well use of from a cluster with Kyverno in action.\n\n#### For more details around the metrics\n\nCheckout the [official docs of Kyverno metrics](https://kyverno.io/docs/monitoring-kyverno-with-prometheus-metrics/)"
   },
   "targets": [
    {}
   ]
  }
 ]
}