{
 "title": "Nexus",
 "tags": [
  "Themengebiet: cicd-tools",
  "Ansprechperson: Tobias Meindl",
  "Applikation: Nexus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(com_sonatype_nexus_plugins_healthcheck_ui_HealthCheckStatusComponent_update_timer,pod)"
    }
   },
   { "name": "log_level", "label": "log_level", "query": "INFO, WARNING, ERROR" }
  ]
 },
 "panels": [
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_total_used{pod=\"$pod\"}",
     "legendFormat": "jvm_memory_used"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"\", namespace=\"gp-cicd-tools\", pod=\"$pod\", container!=\"\", image!=\"\"}) by (container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", cluster=\"\", namespace=\"gp-cicd-tools\", pod=\"$pod\", resource=\"memory\"}\n)",
     "legendFormat": "requested"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"\", namespace=\"gp-cicd-tools\", pod=\"$pod\", resource=\"memory\"}\n)",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"gp-cicd-tools\", pod=\"$pod\", cluster=\"\"}) by (container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", cluster=\"\", namespace=\"gp-cicd-tools\", pod=\"$pod\", resource=\"cpu\"}\n)\n",
     "legendFormat": "requested"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"\", namespace=\"gp-cicd-tools\", pod=\"$pod\", resource=\"cpu\"}\n)",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 22, "w": 13, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{kubernetes_pod_name=~\"$pod\"} |~ `$log_level` | json | line_format `{{.message}}`"
    }
   ]
  },
  {
   "title": "4xx response rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 12 },
   "targets": [
    {
     "expr": "rate(org_eclipse_jetty_webapp_WebAppContext_4xx_responses_total{pod=\"$pod\"}[5m])",
     "legendFormat": "4xx response rate"
    }
   ]
  },
  {
   "title": "5xx response rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 20 },
   "targets": [
    {
     "expr": "rate(org_eclipse_jetty_webapp_WebAppContext_5xx_responses_total{pod=\"$pod\"}[5m])",
     "legendFormat": "5xx response rate"
    }
   ]
  },
  {
   "title": "Repositories",
   "type": "stat",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nexus_analytics_repository_total_count{pod=\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}