{
 "title": "Prometheus Remote Write",
 "tags": [
  "Ansprechperson: Herbert Wirnsberger",
  "Themengebiet: Monitoring"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "prometheusPod",
    "query": "prometheus-k8s-0,prometheus-k8s-1"
   }
  ]
 },
 "panels": [
  {
   "title": "Prometheus Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{kubernetes_pod_name=~\"$prometheusPod\"} | json | line_format \"Level: {{.level}}\\t\\tPod: {{.kubernetes_pod_name}}\\t\\tContainer: {{.kubernetes_container_name}}\\t\\tHost: {{.kubernetes_host}}\\t\\tPodIP: {{.kubernetes_pod_ip}}\\nMessage: {{.message}}\""
    }
   ]
  },
  {
   "title": "Remote Write Behind Sending",
   "type": "timeseries",
   "description": "https://grafana.com/blog/2021/04/12/how-to-troubleshoot-remote-write-issues-in-prometheus/",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(prometheus_remote_storage_highest_timestamp_in_seconds{job=\"prometheus-k8s\"}) by (pod) - sum(prometheus_remote_storage_queue_highest_sent_timestamp_seconds{job=\"prometheus-k8s\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scraped Samples per job",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sort_desc(sum(scrape_samples_scraped) by (job))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shards Desired / Shards Max",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(prometheus_remote_storage_shards_desired{job=\"prometheus-k8s\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "prometheus_remote_storage_shards_max{job=\"prometheus-k8s\",pod=\"prometheus-k8s-0\"}",
     "legendFormat": "Max Shards"
    }
   ]
  }
 ]
}