{
 "title": "PVCs",
 "tags": [
  "Ansprechperson: Simon Gartner",
  "Themengebiet: Storage"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pvc",
    "label": "PVC",
    "query": {
     "query": "label_values(kubelet_volume_stats_available_bytes, persistentvolumeclaim)"
    }
   },
   {
    "name": "days",
    "label": "Days",
    "query": "0,1, 2, 3, 4,5,6,7,8,9,10,11,12,13,14, 21, 31, 62, 365"
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_spec_volumes_persistentvolumeclaims_info{persistentvolumeclaim=~\"$pvc\"} , pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "PVC Available %",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 * ((kubelet_volume_stats_available_bytes{job=\"kubelet\",metrics_path=\"/metrics\",persistentvolumeclaim=~\"$pvc\"} / kubelet_volume_stats_capacity_bytes{job=\"kubelet\",metrics_path=\"/metrics\",persistentvolumeclaim=~\"$pvc\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wie sieht der Speicher in ${days} Tagen aus?",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "quantile_over_time(\n    0.5,\n    predict_linear(\n        kubelet_volume_stats_available_bytes{persistentvolumeclaim=~\"$pvc\"}[7d],\n        ${days} * 24 * 60 * 60\n    )[24h:1h]\n) / kubelet_volume_stats_capacity_bytes",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Access Mode",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "allIsZero" ] } },
   "targets": [
    {
     "expr": "sum by (access_mode)(kube_persistentvolumeclaim_access_mode{persistentvolumeclaim=\"$pvc\"})",
     "legendFormat": "{{access_mode}}"
    }
   ]
  },
  {
   "title": "Mounting Pods",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_spec_volumes_persistentvolumeclaims_info{persistentvolumeclaim=~\"$pvc\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Logs of mounting pod",
   "type": "logs",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "{kubernetes_pod_name=\"$pod\"}"
    }
   ]
  }
 ]
}