{
 "title": "Sonarqube",
 "tags": [
  "Applikation: Sonarqube",
  "Ansprechperson: Tobias Meindl",
  "Themengebiet: cicd-tools"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(sonarqube_asyncexecution_workercount,pod)"
    }
   },
   { "name": "log_level", "label": "log_level", "query": "INFO, WARNING, ERROR" }
  ]
 },
 "panels": [
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 34, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{kubernetes_pod_name=~\"$pod\"} |~ `$log_level` | json | line_format `{{.message}}`"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"gp-cicd-tools\", pod=\"$pod\", cluster=\"\"}) by (container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", cluster=\"\", namespace=\"gp-cicd-tools\", pod=\"$pod\", resource=\"cpu\"}\n)\n",
     "legendFormat": "requested"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"\", namespace=\"gp-cicd-tools\", pod=\"$pod\", container!=\"\", image!=\"\"}) by (container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", cluster=\"\", namespace=\"gp-cicd-tools\", pod=\"$pod\", resource=\"memory\"}\n)\n",
     "legendFormat": "requested"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"\", namespace=\"gp-cicd-tools\", pod=\"$pod\", container!=\"\", image!=\"\"})",
     "legendFormat": "total memory used"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"\", namespace=\"gp-cicd-tools\", pod=\"$pod\", resource=\"memory\"}\n)",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Worker Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sonarqube_asyncexecution_workercount",
     "legendFormat": "Async Worker Count"
    }
   ]
  }
 ]
}