{
 "title": "Vault",
 "tags": [
  "Ansprechperson: Shahin Mahmody",
  "Ansprechperson: Simon Gartner",
  "Themengebiet: Security & Berechtigungen"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "level",
    "query": {}
   },
   {
    "name": "pod",
    "label": "Pod (Logs)",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node Health Score",
   "type": "stat",
   "description": "Score from Autopilot at Leader",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vault_autopilot_node_healthy @ end()",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "Pod Running",
   "type": "stat",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{namespace=\"gp-vault\"} @ end()",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "pod:container_cpu_usage:sum{namespace=\"gp-vault\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Garbage Collection Pauses (ms)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 13, "x": 11, "y": 7 },
     "targets": [
      {
       "expr": "sum(rate(vault_runtime_gc_pause_ns_sum[5m])/1000000) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Claimed",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "sum(vault_runtime_sys_bytes / (1024 * 1024)) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Allocated",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 13, "x": 11, "y": 16 },
     "targets": [
      {
       "expr": "sum(vault_runtime_alloc_bytes/(1024*1024)) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Login Request time (ms)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "sum(rate(vault_core_handle_login_request_sum[5m])) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Requests per second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 8 },
     "targets": [
      {
       "expr": "sum(rate(vault_core_handle_request_count[5m])) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Time to Revoke Tokens",
     "type": "timeseries",
     "description": "Ein hoher Anstieg hier kann gefährlich sein, weil damit Leases länger gültig sind als gewünscht",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "sum(vault_expire_revoke) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Token Creation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 16 },
     "targets": [
      {
       "expr": "sum(increase(vault_token_create_count[5m])) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Timeline",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum(count_over_time({kubernetes_namespace_name=~\"gp-vault\", kubernetes_pod_name=~\".+\"} | json | line_format \"Level: {{.level}} Message: {{.message}}\" |~ \".+\" |~\"\"[500ms]))"
      }
     ]
    },
    {
     "title": "Logs",
     "type": "logs",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "{kubernetes_namespace_name=\"gp-vault\", kubernetes_pod_name=~\"$pod\"} | json | line_format `{{.message}}` | level =~ `$level`"
      }
     ]
    }
   ]
  },
  {
   "title": "Raft Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mögliche Nodeausfälle bez. Quorum",
     "type": "stat",
     "description": "Anzahl Nodes, die Ausfallen können",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "vault_autopilot_failure_tolerance @ end()",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Zeit seit dem letzten Kontakt zu einem Follower",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 3, "y": 10 },
     "targets": [
      {
       "expr": "sum(rate(vault_raft_leader_lastContact_sum[5m])) by (pod)",
       "legendFormat": "{{pod}} (Leader)"
      }
     ]
    },
    {
     "title": "Leadership Lost",
     "type": "timeseries",
     "description": "Zeitspanne, für die eine Vaultinstanz Leader war bevor sie Leadership verloren hat\n\ndiese Metrik wird nicht ausgegeben, es sei denn eine Instanz verliert unerwartet Leadership. Jeder Wert bedeutet, dass etwas einen Leadership Loss verursacht hat, allerdings sind seltene, hohe Werte wahrscheinlich kein Grund zur Sorge, während häufige, niedrige Werte auf ein gravierendes Problem hinweisen",
     "gridPos": { "h": 7, "w": 5, "x": 14, "y": 10 },
     "targets": [
      {
       "expr": "vault_raft_leader_leadership_lost",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Election Fail Times",
     "type": "timeseries",
     "description": "so viel Zeit wurde mit gefailten Elections verbracht\n\nwenn Standbyinstanzen die Leadership nicht übernehmen können, fällt das ganze High-Availability Konzept zusammen, außerdem befindet sich das System, sollten gar keine Elections mehr funktionieren in einem Fehlerzustand, der manuelles Eingreifen vonnöten macht",
     "gridPos": { "h": 7, "w": 5, "x": 19, "y": 10 },
     "targets": [
      {
       "expr": "vault_core_leadership_setup_failed",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Heartbeat Time",
     "type": "timeseries",
     "description": "Time taken to invoke appendEntries on a peer, so that it doesn’t timeout on a periodic basis.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "sum(rate(vault_raft_replication_heartbeat_sum[15m])) by (peer_id)",
       "legendFormat": "{{peer_id}} (Follower)"
      }
     ]
    },
    {
     "title": "Raft Commit Time",
     "type": "timeseries",
     "description": "Time to commit a new entry to the Raft log on the leader.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "sum(rate(vault_raft_commitTime_sum[15m])) by (pod)",
       "legendFormat": "{{pod}} (Leader)"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "PVC available %",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "100 * sum(kubelet_volume_stats_available_bytes{namespace=\"gp-vault\"} / kubelet_volume_stats_capacity_bytes{namespace=\"gp-vault\"}) by (persistentvolumeclaim)",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "BoltDB latency Rate",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "sum (\n    rate (\n        vault_raft_storage_bolt_write_time[15m]\n         )\n) by (database)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Raft PUT",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "sum(vault_raft_storage_put) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Raft GET",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
     "targets": [
      {
       "expr": "sum(vault_raft_storage_get) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Policies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "\"Get Policy\" Latency Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "sum(rate(vault_policy_get_policy_sum[5m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "\"Set Policy\" Latency Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 12 },
     "targets": [
      {
       "expr": "sum(rate(vault_policy_set_policy_sum[5m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "\"Delete Policy\" Latency Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "sum(rate(vault_policy_delete_policy_sum[5m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "\"List Policies\" Latency Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 12 },
     "targets": [
      {
       "expr": "sum(rate(vault_policy_list_policies_sum[5m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Audit Devices",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Audit Response Failure",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "increase(vault_audit_log_response_failure[5m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Audit Request Failures",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "expr": "increase(vault_audit_log_request_failure[5m])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cache Hit/Miss Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "sum(\n    vault_cache_hit / \n    (vault_cache_hit + vault_cache_miss)\n) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Service Tokens verfügbar",
     "type": "stat",
     "gridPos": { "h": 9, "w": 3, "x": 8, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "vault_token_count @ end()", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Standby Node forward errors",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 11, "y": 14 },
     "targets": [
      {
       "expr": "sum(vault_ha_rpc_client_forward_errors) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Leases with expiration",
     "type": "timeseries",
     "description": "Anzahl der Token mit Ablaufdatum\n\nunerwartete Änderungen oder stetiger Anstieg in dieser Metrik können einen Hinweis auf Probleme in der Verwendung von Vault (Client ruft Credential Generation zu oft auf, Time-to-Live zu hoch eingestellt…) hinweisen. Weiters ist sie hilfreich um für Ressourcenverbrauch einen Kontext herzustellen",
     "gridPos": { "h": 9, "w": 7, "x": 17, "y": 14 },
     "targets": [
      { "expr": "sum(vault_expire_num_leases)", "legendFormat": "__auto" }
     ]
    }
   ]
  }
 ]
}