{
 "title": "workflow-dashboard",
 "tags": [
  "Ansprechperson: Constantin Winkler",
  "Themengebiet: CICD"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "workflow",
    "query": {
     "query": "label_values(label_workflows_argoproj_io_workflow)"
    }
   },
   { "name": "pod", "query": { "query": "label_values(pod)" } },
   {
    "name": "container",
    "query": {}
   },
   { "name": "Filters", "label": "Label Filter" },
   { "name": "filter", "label": "Line-Filter" },
   {
    "name": "namespace",
    "query": {
     "query": "kube_pod_info{pod=~\"$pod\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Log Volume", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Step Filter",
   "type": "table",
   "gridPos": { "h": 11, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(kubernetes_labels_template) (count_over_time({kubernetes_pod_name=~\"$pod\"} | json [$__range]))"
    }
   ]
  },
  {
   "title": "Log Level Distribution",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "sum by(level) (rate({kubernetes_pod_name=~\"$workflow-.+\"} |= `$filter` | json [$__interval]))"
    }
   ]
  },
  {
   "title": "Log Volume",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 16, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum by(kubernetes_labels_template) (rate({kubernetes_pod_name=~\"$workflow-.+\"} |= `$filter` | json [$__interval]))",
     "legendFormat": "{{kubernetes_labels_template}}"
    }
   ]
  },
  { "title": "Logs by Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "All Logs",
   "type": "logs",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "{kubernetes_pod_name=~\"$pod\", kubernetes_container_name=~\"$container\"} |= `$filter` | json | line_format `{{printf \"%-26s\" .kubernetes_labels_template}} {{.message}}`",
     "maxLines": 5000
    }
   ]
  },
  {
   "title": "Log per Pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "$pod",
     "type": "logs",
     "gridPos": { "h": 24, "w": 8, "x": 0, "y": 38 },
     "repeat": "pod",
     "targets": [
      {
       "expr": "{kubernetes_pod_name=~\"$pod\", kubernetes_container_name=~\"$container\"} |= `$filter` | json | line_format `{{.message}}` | kubernetes_labels_workflows_argoproj_io_workflow = `$workflow`"
      }
     ]
    }
   ]
  }
 ]
}