---
# Source: gp-cluster-setup/templates/02-argo-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-logging-operator
  finalizers:
  - "resources-finalizer.argocd.argoproj.io"
spec:
  destination:
    namespace: openshift-logging
    server: 'https://kubernetes.default.svc'
  project: gepaplexx
  source:
    chart: gp-cluster-logging-operator
    repoURL: https://gepaplexx.github.io/gp-helm-charts/
    targetRevision: '*'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
...
---
# Source: gp-cluster-setup/templates/02-argo-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-configuration
  finalizers:
  - "resources-finalizer.argocd.argoproj.io"
spec:
  destination:
    namespace: gp-external-secrets
    server: 'https://kubernetes.default.svc'
  project: gepaplexx
  source:
    chart: gp-external-secrets-configuration
    repoURL: https://gepaplexx.github.io/gp-helm-charts/
    targetRevision: '*'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
...
---
# Source: gp-cluster-setup/templates/02-argo-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-operator
  finalizers:
  - "resources-finalizer.argocd.argoproj.io"
spec:
  destination:
    namespace: grafana-operator-system
    server: 'https://kubernetes.default.svc'
  project: gepaplexx
  source:
    chart: gp-grafana-operator
    repoURL: https://gepaplexx.github.io/gp-helm-charts/
    targetRevision: '*'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
...
---
# Source: gp-cluster-setup/templates/02-argo-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-instance
  finalizers:
  - "resources-finalizer.argocd.argoproj.io"
spec:
  destination:
    namespace: gp-sso
    server: 'https://kubernetes.default.svc'
  project: gepaplexx
  source:
    chart: gp-keycloak-instance
    helm:
      parameters:
      - name: features.enabled
        value: openshift-integration,token_exchange,impersonation,admin_fine_grained_authz
      - name: ingress.hostname
        value: sso.apps.play.gepaplexx.com
      - name: persistence.auth.password
        value: AgBsTRVF6DGROo0dOE+iKgmOGfnfsJDfRND4ReJpEL5GCpECGQB8jVUCmjWBJ7pr4KyC/F5JEYfGDds9AVlaRNpDioSVUVJDG4i5oOw2ZxWSXC+3+xQYpmOBITLQ191eWAjtWyeMsEwl4Hl/kQHcIzKH7eFRJh9mbBv4fXpUJCQS/Ej1CdKBOcNz3l3Xq39vX2zbysVaCTqAPRKtZb7KzFH6CTwNYS43Ck4tO53BMeMXLSk0TFQjQUvscvqGEYB4SQbf0t2gWatn+bSwJttBGKm6qJO5YgBiWRQdObN5h22czeyYiVoSnUgumGwxETIlaWt+COTP7OyfyHjVcmVkM2KQZDcOF3uR2u8QTgmcIoDPYL5zS6hZO5eY6PkazfWbsezIcbtHRFuLYE/6QjedRyqCCrHfJJdHz11P+KpaIJ2XhbpLAnAxgkBdNPG8djeDnFCNjILz8t2HctAnN6P1gcxPIOPNxYwGzCf4FISVMb/vFqBJazVMlET6NnCIUKH6coW1jPbsVbi68tGiYQk4Y0FykdMnTAoueJqf/sucQ67DkY3XTtHfDtOd5eHIirIEm8sivdRXu4kIA5U/tgdOAX3hTJmUbp2ZcqJcCA0mlsOcAsmiCGtClxaZ8KU681rU1pad2f84QgiNYiJAO+NsgdM1Hcu633z2FXlMUeLtHWvs5ptvjIAe4X9Ekn2RkRivpWSDhJrM/DGxCBZhsNuHHFXZDrpcpJbGnnHC0ShqQtD1jg==
      - name: provider.openshift.clientSecret
        value: AgCOOc9m+zqrK68KKGoLwsxxTGHrjyeX+5Ih8QrkjKsegb+/Qxxo/tZb2J+FzmXo0VBNgJvY9fGe8XbBhUDuCsbCwsGZAtNdhC6AJwNwqcqEVn5pRsDib79J88ncRjREhNdt+I6v4PIRVgr+lASsU8OKbA9+bMKHRPxkZSQPU37Mj6liJFtCAcBW98sXysSE1/ZpIAizeAEuonuEVsMdJ3esvfI6l5chK9Bw6LQjuzQuOrkdEE5ibXD4ax7AdpC2xhPEuwTyOclptJkeUIzfE4jAEJg6gf7D1zEbERL/qtI3Mj0XRlCES1RFDwEjoiuLQyfOq2Mf3r67mE63r7myqlNJpnszmHPHD2f8wt2sIQrOq2h3B8t0WLYFiVXRV+qF9Puf7jAdUFca/I+3c0y14R/VeClCQBxhSoDuxg+pb03wnQcDWVcid2s6vpGoEOciAkp1HiuJi8BkCYFUIqNarrIDxEATaHORvDiM/cgohVH014dxp3MQleA5IOyMkZEFKmJIM986xFcldONMneQqh8whcCp2v9sujYHZSCLd+ehfqujIhqi25iaQ/IuKrVQtPYjd3AMilcw4PD3TXVJxj/AKOyxIk9eNDRwSAgR5FJVs2vkOWIR+IlwLExGzH4kFG+kJhWm6k20vURy35S5NjBSk9haaTKi7iRG9tMQRB6tdyIIdGjtjfrZJv3W9Fdg+eSGRfKqRXpFUSDUwhuMngf/cv78LW7jeDIOtfzZkSTeUG/xt0CHF
    repoURL: https://gepaplexx.github.io/gp-helm-charts/
    targetRevision: '*'
  ignoreDifferences:
    - group: oauth.openshift.io
      jsonPointers:
      - /secret
      kind: OAuthClient
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
...
---
# Source: gp-cluster-setup/templates/02-argo-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  finalizers:
  - "resources-finalizer.argocd.argoproj.io"
spec:
  destination:
    namespace: gp-cluster-policies
    server: 'https://kubernetes.default.svc'
  project: gepaplexx
  source:
    chart: gp-kyverno
    repoURL: https://gepaplexx.github.io/gp-helm-charts/
    targetRevision: '*'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
...
---
# Source: gp-cluster-setup/templates/02-argo-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph-instance
  finalizers:
  - "resources-finalizer.argocd.argoproj.io"
spec:
  destination:
    namespace: rook-ceph
    server: 'https://kubernetes.default.svc'
  project: gepaplexx
  source:
    chart: gp-storage-cephcluster
    repoURL: https://gepaplexx.github.io/gp-helm-charts/
    targetRevision: '*'
  ignoreDifferences:
    - group: ceph.rook.io
      jsonPointers:
      - /spec/monitoring/createPrometheusRules
      kind: CephCluster
      name: rook-ceph
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
...
