{
 "title": "Kubeapi server zerklauben",
 "tags": [ "owner: Constantin Winkler" ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "KubeApi requests rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate((apiserver_request_total{namespace=\"openshift-apiserver\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KubeApi requests by api",
   "type": "timeseries",
   "gridPos": { "h": 23, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(api) (rate({kubernetes_pod_name=~\"apiserver.+|kube-apiserver-.+\"} |= `Trace` != `GuaranteedUpdate` != `recursive` |~ `List|Get|Update|Delete|Patch|Create` |= `apirequestcounts` | json | level = `info` | line_format `{{.message}}` | pattern `<_> <_> <_> <_> Trace[<traceid>]: \"<method>\" url:<url>,user-agent:<useragent> <_>` | line_format `{{.url}}` | pattern `<_>/apis/apiserver.openshift.io/v1/apirequestcounts/<ns>/` | line_format `{{.ns}}` | pattern `<_>.<_>.<api>` [$__interval]))"
    }
   ]
  },
  {
   "title": "Kubeapi namespace cpu ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "namespace:container_cpu_usage:sum{namespace=\"openshift-kube-apiserver\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KubeApi requests by namespace",
   "type": "timeseries",
   "gridPos": { "h": 23, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(ns) (rate({kubernetes_pod_name=~\"apiserver.+|kube-apiserver-.+\"} |= `Trace` != `GuaranteedUpdate` != `recursive` |~ `List|Get|Update|Delete|Patch|Create` | json | level = `info` | line_format `{{.message}}` | pattern `<_> <_> <_> <_> Trace[<traceid>]: \"<method>\" url:<url>,user-agent:<useragent> <trace2>` | line_format `{{.url}}` | pattern `<_>/api/v1/namespaces/<ns>/` | line_format `{{.url}}` | pattern `<_>/apis/<ns>/` | pattern `<_>/apis/apps/v1/namespaces/<ns>/` | pattern `<_>/apis/<api>/<_>/<ns>/` | pattern `<_>/apis/<api>/<_>/namespaces/<ns>/` [$__interval]))"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "{kubernetes_pod_name=~\"apiserver.+|kube-apiserver-.+\"} |= `Trace` != `GuaranteedUpdate` != `recursive` |~ `List|Get|Update|Delete|Patch|Create` | json | level = `info` | line_format `{{.message}}` | pattern `<_> <_> Trace[<traceid>]: <uff>` | line_format `{{.traceid}}: {{.uff}}`"
    }
   ]
  }
 ]
}