{{- range .Values.applications}}
{{- with . }}
{{- if (eq .enabled true)}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  finalizers:
  - "resources-finalizer.argocd.argoproj.io"
spec:
  destination:
    {{- if (.destination.namespace ) }}
    namespace: {{ .destination.namespace }}
    {{- end }}
    server: 'https://kubernetes.default.svc'
  project: {{ default "default" $.Values.project.name }}
  source:
{{ toYaml .source | indent 4 }}
{{- if .ignoreDifferences }}
  ignoreDifferences:
{{ toYaml .ignoreDifferences | indent 4 }}
{{- end }}
  syncPolicy:
    {{- if .syncPolicy.automated }}
    automated:
      prune: {{ .syncPolicy.automated.prune }}
      selfHeal: {{ .syncPolicy.automated.selfHeal }}
    {{- end }}
    syncOptions:
      - CreateNamespace={{ .destination.create }}
...
{{- end }}
{{- end }}
{{- end }}
